version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: ecommerce_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: 1234
    

