
/*
    -> 1***: USERS ERRORS
    -> 2***: REQ PROCESSAMENT ERRORS
    -> 3***: INTERNAL SERVER ERRORS
    -> 4***: AUTHORIZATION ERRORS
    -> 5***: PRODUCTS ERRORS
    -> 6***: Cart ERRORS
    -> 7***: Order ERRORS
*/

export enum ErrorCodes {
    USER_NOT_FOUND = 1001,
    USER_ALREADY_EXISTS = 1002,
    INCORRECT_LOGIN = 1003,
    
    ADDRESS_NOT_FOUND= 10040,
    BILLING_ADDRESS_NOT_FOUND= 10041,
    SHIPPING_ADDRESS_NOT_FOUND= 10042,

    UNPROCESSABLE_ENTITY = 2001,

    INTERNAL_SERVER_ERROR = 3001,

    UNAUTHORIZED = 4001,

    PRODUCT_NOT_FOUND= 5001,

    CART_NOT_FOUND=6001,
    EMPTY_CART=6002,

    ORDER_NOT_FOUND=7001
}